/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JX4KWshlnrR
 */
import Link from "next/link"

export function Section1() {
  return (
    <div className="flex h-screen w-16 border-r flex-col shrink-0 items-stretch">
      <div className="flex-1 grid place-items-center">
        <Link className="flex flex-col items-center rounded-full p-2 hover:bg-gray-100 dark:hover:bg-gray-800" href="#">
          <BookIcon className="h-6 w-6" />
          <span className="text-2xs font-medium leading-none mt-1">Docs</span>
        </Link>
      </div>
      <div className="flex-1 grid place-items-center">
        <Link className="flex flex-col items-center rounded-full p-2 hover:bg-gray-100 dark:hover:bg-gray-800" href="#">
          <BarChartIcon className="h-6 w-6" />
          <span className="text-2xs font-medium leading-none mt-1">Analytics</span>
        </Link>
      </div>
      <div className="flex-1 grid place-items-center">
        <Link className="flex flex-col items-center rounded-full p-2 hover:bg-gray-100 dark:hover:bg-gray-800" href="#">
          <HelpCircleIcon className="h-6 w-6" />
          <span className="text-2xs font-medium leading-none mt-1">Tickets</span>
        </Link>
      </div>
    </div>
  )
}


function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function BarChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}


function HelpCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </svg>
  )
}
